---
title: England is my city
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: florianpelloux85@gmail.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: pomme_de_pain
url: ''
twitter_username: Jean-Gontrand
github_username: Oui.
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
algolia:
  application_id: 97DCTMLLSW
  index_name: DOJ85
